### ISSUE TITLE
Crash on linux when using mupdf with another crate which also uses the freetype library

### ISSUE THREAD

**Issue by dyaso** [messense/mupdf-rs#20]
I'm trying to render pages with mupdf then draw them in a [Druid UI toolkit](https://github.com/linebender/druid) window (which works!) but as soon as I try to draw any text with druid my program crashes, I assume because it and mupdf are trying to use freetype in incompatible ways?

This isn't a huge issue as I mostly want to use the program I'm writing on Windows, and this problem shouldn't occur there as Druid would be using Direct2D/DirectWrite instead of freetype. It would be nice to be able to write my program under linux, tho

```
Feb 20 04:15:28.019  INFO druid_shell::platform::gtk::application: gtk: Activated application
[src/pdf_view.rs:111] size = 1100.0W×951.0H
thread 'main' panicked at 'Failed to restore: FreetypeError', /home/oliver/.cargo/registry/src/github.com-1ecc6299db9ec823/cairo-rs-0.9.1/src/context.rs:174:23
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::expect
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/result.rs:933:23
   4: cairo::context::Context::restore
             at /home/oliver/.cargo/registry/src/github.com-1ecc6299db9ec823/cairo-rs-0.9.1/src/context.rs:174:9
   5: <piet_cairo::CairoRenderContext as piet::render_context::RenderContext>::restore
             at /home/oliver/.cargo/registry/src/github.com-1ecc6299db9ec823/piet-cairo-0.3.0/src/lib.rs:177:13
   6: druid::contexts::PaintCtx::with_save
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid/src/contexts.rs:774:25
   7: <pdf_progress_tracker::pdf_view::PdfVu as druid::widget::widget::Widget<pdf_progress_tracker::PdfViewWindow>>::paint
             at ./src/pdf_view.rs:157:9
   8: <alloc::boxed::Box<dyn druid::widget::widget::Widget<T>> as druid::widget::widget::Widget<T>>::paint
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid/src/widget/widget.rs:255:9
   9: druid::core::WidgetPod<T,W>::paint_raw
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid/src/core.rs:422:9
  10: druid::window::Window<T>::paint::{{closure}}
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid/src/window.rs:443:51
  11: druid::contexts::PaintCtx::with_child_ctx
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid/src/contexts.rs:741:9
  12: druid::window::Window<T>::paint
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid/src/window.rs:443:9
  13: druid::window::Window<T>::do_paint
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid/src/window.rs:378:9
  14: druid::win_handler::Inner<T>::paint
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid/src/win_handler.rs:329:13
  15: druid::win_handler::AppState<T>::paint_window
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid/src/win_handler.rs:548:9
  16: <druid::win_handler::DruidHandler<T> as druid_shell::window::WinHandler>::paint
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid/src/win_handler.rs:842:9
  17: druid_shell::platform::gtk::window::WindowBuilder::build::{{closure}}::{{closure}}
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid-shell/src/platform/gtk/window.rs:408:25
  18: druid_shell::platform::gtk::window::WindowState::with_handler_and_dont_check_the_other_borrows
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid-shell/src/platform/gtk/window.rs:716:31
  19: druid_shell::platform::gtk::window::WindowBuilder::build::{{closure}}
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid-shell/src/platform/gtk/window.rs:395:21
  20: <O as gtk::auto::widget::WidgetExt>::connect_draw::draw_trampoline
             at /home/oliver/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.9.2/src/auto/widget.rs:3747:13
  21: _gtk_marshal_BOOLEAN__BOXEDv
  22: gtk_widget_draw_marshallerv
  23: _g_closure_invoke_va
  24: g_signal_emit_valist
  25: g_signal_emit
  26: gtk_widget_draw_internal
  27: gtk_container_propagate_draw
  28: gtk_container_draw
  29: gtk_box_draw_contents
  30: gtk_css_custom_gadget_draw
  31: gtk_css_gadget_draw
  32: gtk_box_draw
  33: gtk_widget_draw_internal
  34: gtk_container_propagate_draw
  35: gtk_container_draw
  36: gtk_window_draw
  37: gtk_widget_draw_internal
  38: gtk_widget_render
  39: gtk_main_do_event
  40: _gdk_event_emit
  41: _gdk_window_process_updates_recurse_helper
  42: gdk_window_process_updates_internal
  43: gdk_window_process_updates_with_mode
  44: _g_closure_invoke_va
  45: g_signal_emit_valist
  46: g_signal_emit
  47: gdk_frame_clock_paint_idle
  48: gdk_threads_dispatch
  49: g_timeout_dispatch
  50: g_main_context_dispatch
  51: g_main_context_iterate.constprop.0
  52: g_main_context_iteration
  53: g_application_run
  54: <O as gio::application::ApplicationExtManual>::run
             at /home/oliver/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.9.1/src/application.rs:23:13
  55: druid_shell::platform::gtk::application::Application::run
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid-shell/src/platform/gtk/application.rs:65:9
  56: druid_shell::application::Application::run
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid-shell/src/application.rs:153:9
  57: druid::app::AppLauncher<T>::launch
             at /home/oliver/.cargo/git/checkouts/druid-f71533f3d81c0bc8/47fb9fb/druid/src/app.rs:263:9
  58: pdf_progress_tracker::main
             at ./src/main.rs:201:5
  59: core::ops::function::FnOnce::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by messense** [comment]
Do you have a repository that I can play with?

**Comment by dyaso** [comment]
I made a minimal example https://github.com/dyaso/pdf-druid-freetype-conflict

**Comment by messense** [comment]
Just try on macOS, `cargo run --features=mupdf` works fine. Will try Linux later.

**Comment by messense** [comment]
@dyaso Can you try master branch with `sys-lib-freetype` feature turned on?

**Comment by dyaso** [comment]
That works, thanks for fixing it so quickly.

**Comment by messense** [comment]
Released in https://crates.io/crates/mupdf/0.1.1
